name: Lint

on:
  push:
  pull_request:

jobs:
  rustfmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rustfmt
        run: cargo fmt --all -- --check

  clippy:
    name: Common mistakes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clippy
        run: cargo clippy --all-features
